"""
Application constants.

Centralized location for all constant values used throughout the application.
"""

# Job statuses
JOB_STATUS_QUEUED = 'queued'
JOB_STATUS_RUNNING = 'running'
JOB_STATUS_SUCCESS = 'success'
JOB_STATUS_FAILED = 'failed'
JOB_STATUS_TIMEOUT = 'timeout'
JOB_STATUS_CANCELLED = 'cancelled'

JOB_STATUSES = [
    JOB_STATUS_QUEUED,
    JOB_STATUS_RUNNING,
    JOB_STATUS_SUCCESS,
    JOB_STATUS_FAILED,
    JOB_STATUS_TIMEOUT,
    JOB_STATUS_CANCELLED,
]

# Schedule types
SCHEDULE_TYPE_INTERVAL = 'interval'
SCHEDULE_TYPE_CRON = 'cron'
SCHEDULE_TYPE_ONCE = 'once'

SCHEDULE_TYPES = [
    SCHEDULE_TYPE_INTERVAL,
    SCHEDULE_TYPE_CRON,
    SCHEDULE_TYPE_ONCE,
]

# Device statuses
DEVICE_STATUS_ONLINE = 'online'
DEVICE_STATUS_OFFLINE = 'offline'
DEVICE_STATUS_UNKNOWN = 'unknown'

# Protocol statuses
PROTOCOL_STATUS_YES = 'YES'
PROTOCOL_STATUS_NO = 'NO'

# Targeting sources
TARGETING_DATABASE_QUERY = 'database_query'
TARGETING_GROUP = 'group'
TARGETING_STATIC = 'static'
TARGETING_NETWORK_RANGE = 'network_range'

TARGETING_SOURCES = [
    TARGETING_DATABASE_QUERY,
    TARGETING_GROUP,
    TARGETING_STATIC,
    TARGETING_NETWORK_RANGE,
]

# Executor types
EXECUTOR_SSH = 'ssh'
EXECUTOR_SNMP = 'snmp'
EXECUTOR_PING = 'ping'
EXECUTOR_HTTP = 'http'

EXECUTOR_TYPES = [
    EXECUTOR_SSH,
    EXECUTOR_SNMP,
    EXECUTOR_PING,
    EXECUTOR_HTTP,
]

# Action types
ACTION_INTERFACE_DISCOVERY = 'interface_discovery'
ACTION_OPTICAL_POWER_MONITORING = 'optical_power_monitoring'
ACTION_NETWORK_DISCOVERY = 'network_discovery'
ACTION_PING_HOST = 'ping_host'
ACTION_LLDP_DISCOVERY = 'lldp_discovery'
ACTION_CUSTOM_COMMAND = 'custom_command'

ACTION_TYPES = [
    ACTION_INTERFACE_DISCOVERY,
    ACTION_OPTICAL_POWER_MONITORING,
    ACTION_NETWORK_DISCOVERY,
    ACTION_PING_HOST,
    ACTION_LLDP_DISCOVERY,
    ACTION_CUSTOM_COMMAND,
]

# Database operation types
DB_OPERATION_INSERT = 'insert'
DB_OPERATION_UPSERT = 'upsert'
DB_OPERATION_UPDATE = 'update'

DB_OPERATIONS = [
    DB_OPERATION_INSERT,
    DB_OPERATION_UPSERT,
    DB_OPERATION_UPDATE,
]

# System job definition IDs (well-known UUIDs)
SYSTEM_JOB_NETWORK_DISCOVERY = '11111111-1111-1111-1111-111111111111'
SYSTEM_JOB_PING_HOST = '22222222-2222-2222-2222-222222222222'
SYSTEM_JOB_INTERFACE_SCAN = '33333333-3333-3333-3333-333333333333'
SYSTEM_JOB_INTERFACE_DISCOVERY = '44444444-4444-4444-4444-444444444444'
SYSTEM_JOB_LLDP_DISCOVERY = '55555555-5555-5555-5555-555555555555'
SYSTEM_JOB_OPTICAL_POWER = '66666666-6666-6666-6666-666666666666'

SYSTEM_JOB_IDS = [
    SYSTEM_JOB_NETWORK_DISCOVERY,
    SYSTEM_JOB_PING_HOST,
    SYSTEM_JOB_INTERFACE_SCAN,
    SYSTEM_JOB_INTERFACE_DISCOVERY,
    SYSTEM_JOB_LLDP_DISCOVERY,
    SYSTEM_JOB_OPTICAL_POWER,
]

# Default time ranges (in hours)
TIME_RANGE_1_HOUR = 1
TIME_RANGE_6_HOURS = 6
TIME_RANGE_24_HOURS = 24
TIME_RANGE_7_DAYS = 168
TIME_RANGE_30_DAYS = 720
TIME_RANGE_90_DAYS = 2160

# Pagination defaults
DEFAULT_PAGE_SIZE = 50
MAX_PAGE_SIZE = 500

# Celery task names
CELERY_TASK_JOB_RUN = 'opsconductor.job.run'
CELERY_TASK_SCAN = 'opsconductor.scan'
